import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import DashboardNav from "@/components/navigation/dashboard-nav";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  variable: "--font-poppins",
  display: 'swap',
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body className="flex flex-col h-screen font-sans">
        <DashboardNav />
        <div className="w-full h-full flex-1 overflow-auto">{children}</div>
      </body>
    </html>
  );
}