version: "3"
services:
  kendo-backend:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    command: npm run dev
